### 分页查询课程信息
POST {{content_host}}/content/course/list?pageNo=2&pageSize=2
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus": ""
}

###查询课程分类
GET {{content_host}}/content/course-category/tree-nodes

### 创建课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201001",
  "price": 10,
  "originalPrice":100,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "",
  "pic": "fdg",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "",
  "grade": "204001",
  "description": "aaaaa"
}

### 课程查询
GET {{content_host}}/content/course/40
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE3MTQyNzczMjksImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6ImRkM2FiNTkwLTFhYzUtNGM0ZS04NTc3LTBhMWM2YWVjNmJiMyIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.jgxF9BkFEcf_fozlQ30ZiguyrvVI1Gbbch096H-QwOI

### 通过网关课程查询
GET {{gateway_host}}/content/course/40
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJiaXJ0aGRheVwiOlwiMjAyMi0wOS0yOFQxOToyODo0NlwiLFwiY3JlYXRlVGltZVwiOlwiMjAyMi0wOS0yOFQwODozMjowM1wiLFwiaWRcIjpcIjUwXCIsXCJuYW1lXCI6XCLlrabnlJ8xXCIsXCJuaWNrbmFtZVwiOlwi5aSn5rC054mbXCIsXCJzZXhcIjpcIjFcIixcInN0YXR1c1wiOlwiMVwiLFwidXNlcm5hbWVcIjpcInN0dTFcIixcInVzZXJwaWNcIjpcImh0dHA6Ly9maWxlLjUxeHVlY2hlbmcuY24vZGRkZlwiLFwidXR5cGVcIjpcIjEwMTAwMVwifSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE3MTQyODAzNjMsImF1dGhvcml0aWVzIjpbInRlc3QiXSwianRpIjoiZTZkODk4ZDEtY2IyMC00NzRkLWFmYzEtYmQ0YjEzZDcwNDFlIiwiY2xpZW50X2lkIjoiWGNXZWJBcHAifQ.hiLFPR61ptFRgombDgL0kdgGRTW58fESQUYLU5L5dBg

### 课程计划查询
GET {{content_host}}/content/teachplan/26/tree-nodes

### 课程计划绑定视频
POST {{media_host}}/media/teachplan/association/media
Content-Type: application/json

{
  "mediaId": "",
  "fileName": "",
  "teachplanId": ""
}


<> 2024-03-12T010806.200.json